// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// tdm
List tdm(const StringVector strings, const bool remove_digits, const std::vector<std::string> stopwords, const std::vector<std::string> dictionary, const int min_term_freq, const int max_term_freq, const int min_word_length, const int max_word_length);
RcppExport SEXP tm_tdm(SEXP stringsSEXP, SEXP remove_digitsSEXP, SEXP stopwordsSEXP, SEXP dictionarySEXP, SEXP min_term_freqSEXP, SEXP max_term_freqSEXP, SEXP min_word_lengthSEXP, SEXP max_word_lengthSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const StringVector >::type strings(stringsSEXP);
    Rcpp::traits::input_parameter< const bool >::type remove_digits(remove_digitsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type stopwords(stopwordsSEXP);
    Rcpp::traits::input_parameter< const std::vector<std::string> >::type dictionary(dictionarySEXP);
    Rcpp::traits::input_parameter< const int >::type min_term_freq(min_term_freqSEXP);
    Rcpp::traits::input_parameter< const int >::type max_term_freq(max_term_freqSEXP);
    Rcpp::traits::input_parameter< const int >::type min_word_length(min_word_lengthSEXP);
    Rcpp::traits::input_parameter< const int >::type max_word_length(max_word_lengthSEXP);
    __result = Rcpp::wrap(tdm(strings, remove_digits, stopwords, dictionary, min_term_freq, max_term_freq, min_word_length, max_word_length));
    return __result;
END_RCPP
}
